#!/usr/bin/env bash
# Stop hook: auto-save basic checkpoint to .lifecycle/checkpoints/
# Captures branch, task progress, and recent files — NOT cognitive state.
# For full cognitive checkpoints, users should run /checkpoint manually.
# Token cost: 0 (command hook, no LLM)
set -euo pipefail

# Read CWD from stdin JSON (Stop hook provides it)
INPUT="$(cat)"
CWD="$(echo "$INPUT" | sed -n 's/.*"cwd" *: *"\([^"]*\)".*/\1/p')"
CWD="${CWD//\\//}"

if [[ -z "$CWD" ]]; then
  CWD="$(pwd)"
  CWD="${CWD//\\//}"
fi

LIFECYCLE_DIR="$CWD/.lifecycle"
CHECKPOINT_DIR="$LIFECYCLE_DIR/checkpoints"
PLANS_DIR="$LIFECYCLE_DIR/plans"

# Only run if this project uses .lifecycle/
[[ -d "$LIFECYCLE_DIR" ]] || exit 0

# Find active progress file (has [ ] or [~] tasks)
ACTIVE_PROGRESS=""
FEATURE_NAME=""
if [[ -d "$PLANS_DIR" ]]; then
  for f in "$PLANS_DIR"/*-progress.md; do
    [[ -f "$f" ]] || continue
    if grep -qE '^\[[ ~]\]' "$f" 2>/dev/null; then
      ACTIVE_PROGRESS="$f"
      # Extract feature name from filename: foo-progress.md → foo
      FEATURE_NAME="$(basename "$f" | sed 's/-progress\.md$//')"
      break
    fi
  done
fi

# Nothing active = nothing to checkpoint
[[ -n "$ACTIVE_PROGRESS" ]] || exit 0

mkdir -p "$CHECKPOINT_DIR"

NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Count task progress
TOTAL=$(grep -cE '^\[.\]' "$ACTIVE_PROGRESS" 2>/dev/null) || TOTAL=0
DONE=$(grep -cE '^\[x\]' "$ACTIVE_PROGRESS" 2>/dev/null) || DONE=0

# Find current/next task
NEXT_TASK="$(grep -m1 -E '^\[[ ~]\]' "$ACTIVE_PROGRESS" | sed 's/^\[.\] //' || echo "unknown")"

# Get branch
BRANCH="unknown"
if git -C "$CWD" rev-parse --git-dir &>/dev/null; then
  BRANCH="$(git -C "$CWD" branch --show-current 2>/dev/null || echo "detached")"
  [[ -n "$BRANCH" ]] || BRANCH="detached"
fi

# Get last commit (if any)
LAST_COMMIT=""
if git -C "$CWD" rev-parse --git-dir &>/dev/null; then
  LAST_COMMIT="$(git -C "$CWD" log -1 --format='%h %s' 2>/dev/null || true)"
fi

# Get recently modified files from active-changes.log (if hooks are running)
RECENT_FILES=""
LOG="$HOME/.claude/sessions/active-changes.log"
if [[ -f "$LOG" ]]; then
  RECENT_FILES="$(grep -E ' (Edit|Write) ' "$LOG" | awk '{print $3}' | sort -u | tail -10 | sed 's/^/- /' || true)"
fi

# Write auto-checkpoint (overwrites previous for same feature)
CHECKPOINT_FILE="$CHECKPOINT_DIR/${FEATURE_NAME}-checkpoint.md"

cat > "$CHECKPOINT_FILE" << EOF
# Checkpoint: $FEATURE_NAME
**Saved:** $NOW (auto)
**Task:** $NEXT_TASK
**Progress:** $DONE/$TOTAL tasks complete
**Branch:** $BRANCH

## Last Commit
${LAST_COMMIT:-No commits this session}

## Recent Files
${RECENT_FILES:-No file tracking data (install session hooks for this)}

---
*Auto-generated by Continuum stop hook. For full cognitive checkpoints with reasoning and decisions, run /checkpoint manually.*
EOF

# Append session summary to activity log
ACTIVITY_FILE="$LIFECYCLE_DIR/activity.md"

# Count files changed this session
FILE_COUNT=0
if [[ -f "$LOG" ]]; then
  FILE_COUNT="$(grep -cE ' (Edit|Write) ' "$LOG" 2>/dev/null)" || FILE_COUNT=0
fi

# Build activity line
ACTIVITY_LINE="- [$NOW] $FEATURE_NAME — $DONE/$TOTAL tasks, branch: $BRANCH, files: $FILE_COUNT"

# Create file with header if it doesn't exist
if [[ ! -f "$ACTIVITY_FILE" ]]; then
  echo "# Activity Log" > "$ACTIVITY_FILE"
  echo "" >> "$ACTIVITY_FILE"
fi

# Insert new entry after header, trim to 20 entries
{ head -2 "$ACTIVITY_FILE"; echo "$ACTIVITY_LINE"; tail -n +3 "$ACTIVITY_FILE" | head -19; } > "$ACTIVITY_FILE.tmp" && mv "$ACTIVITY_FILE.tmp" "$ACTIVITY_FILE"

exit 0
